# Generated by Django 6.0.2 on 2026-02-12 02:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeclock', '0003_activityreportrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punch',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
