# Generated by Django 6.0.2 on 2026-02-14

from django.db import migrations, models


def deactivate_duplicated_active_contracts(apps, schema_editor):
    Contract = apps.get_model("timeclock", "Contract")
    active_contracts = (
        Contract.objects.filter(is_active=True)
        .order_by("company_id", "employee_user_id", "-created_at", "-id")
    )

    seen_pairs = set()
    to_deactivate_ids = []
    for contract in active_contracts.iterator():
        pair = (contract.company_id, contract.employee_user_id)
        if pair in seen_pairs:
            to_deactivate_ids.append(contract.id)
            continue
        seen_pairs.add(pair)

    if to_deactivate_ids:
        Contract.objects.filter(id__in=to_deactivate_ids).update(is_active=False)


class Migration(migrations.Migration):

    dependencies = [
        ("timeclock", "0004_alter_punch_timestamp"),
    ]

    operations = [
        migrations.RunPython(
            deactivate_duplicated_active_contracts,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="contract",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("company", "employee_user"),
                name="unique_active_contract_per_company_employee",
            ),
        ),
    ]
