# Generated by Codex on 2026-03-24

import django.db.models.deletion
from django.db import migrations, models


def backfill_contract_employee(apps, schema_editor):
    Contract = apps.get_model("timeclock", "Contract")
    Employee = apps.get_model("companies", "Employee")

    for contract in Contract.objects.select_related("employee_user", "company").iterator():
        employee = Employee.objects.filter(user_id=contract.employee_user_id).first()
        if not employee:
            user = contract.employee_user
            full_name = (f"{(user.first_name or '').strip()} {(user.last_name or '').strip()}").strip()
            if not full_name:
                full_name = (user.username or user.email or "Funcionario").strip()
            employee = Employee.objects.create(
                user_id=user.id,
                company_id=contract.company_id,
                full_name=full_name,
                is_active=True,
            )
        elif employee.company_id != contract.company_id and not employee.company_id:
            employee.company_id = contract.company_id
            employee.save(update_fields=["company"])

        contract.employee_id = employee.id
        contract.save(update_fields=["employee"])


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0006_enforce_employee_company_required"),
        ("timeclock", "0006_punch_is_manual"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contract_employee_temp",
                to="companies.employee",
            ),
        ),
        migrations.RunPython(backfill_contract_employee, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name="contract",
            name="unique_active_contract_per_company_employee",
        ),
        migrations.RemoveField(
            model_name="contract",
            name="employee_user",
        ),
        migrations.AlterField(
            model_name="contract",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contracts",
                to="companies.employee",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contracts",
                to="companies.company",
            ),
        ),
        migrations.AddConstraint(
            model_name="contract",
            constraint=models.UniqueConstraint(
                condition=models.Q(is_active=True),
                fields=("company", "employee"),
                name="unique_active_contract_per_company_employee",
            ),
        ),
    ]
