# Generated by Codex on 2026-03-24

import django.db.models.deletion
from django.db import migrations, models


def backfill_report_employee(apps, schema_editor):
    ActivityReportRequest = apps.get_model("timeclock", "ActivityReportRequest")
    Employee = apps.get_model("companies", "Employee")

    for request_obj in ActivityReportRequest.objects.select_related("employee_user", "company").iterator():
        employee = Employee.objects.filter(user_id=request_obj.employee_user_id).first()
        if not employee:
            user = request_obj.employee_user
            full_name = (f"{(user.first_name or '').strip()} {(user.last_name or '').strip()}").strip()
            if not full_name:
                full_name = (user.username or user.email or "Funcionario").strip()
            employee = Employee.objects.create(
                user_id=user.id,
                company_id=request_obj.company_id,
                full_name=full_name,
                is_active=True,
            )
        elif not employee.company_id:
            employee.company_id = request_obj.company_id
            employee.save(update_fields=["company"])

        request_obj.employee_id = employee.id
        request_obj.save(update_fields=["employee"])


class Migration(migrations.Migration):

    dependencies = [
        ("timeclock", "0007_contract_employee_fk_required"),
        ("companies", "0006_enforce_employee_company_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="activityreportrequest",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="activity_report_requests_employee_temp",
                to="companies.employee",
            ),
        ),
        migrations.RunPython(backfill_report_employee, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="activityreportrequest",
            name="employee_user",
        ),
        migrations.AlterField(
            model_name="activityreportrequest",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="activity_report_requests",
                to="companies.employee",
            ),
        ),
    ]
