# Generated by Django 6.0.2 on 2026-04-18 15:45

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_seed_plans_features'),
        ('timeclock', '0008_activity_report_employee_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_date', models.DateField(default=django.utils.timezone.localdate)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_reports', to='companies.company')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_reports', to='timeclock.contract')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_reports', to='companies.employee')),
            ],
            options={
                'ordering': ['-report_date', '-created_at'],
                'indexes': [models.Index(fields=['company', 'report_date'], name='timeclock_s_company_aa849f_idx'), models.Index(fields=['employee', 'report_date'], name='timeclock_s_employe_9395a2_idx'), models.Index(fields=['contract', 'report_date'], name='timeclock_s_contrac_aeefa1_idx')],
            },
        ),
    ]
