# Generated by Django 6.0.2 on 2026-04-18 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_activity_request_status(apps, schema_editor):
    ActivityReportRequest = apps.get_model("timeclock", "ActivityReportRequest")
    for request_obj in ActivityReportRequest.objects.all().iterator():
        update_fields = []
        if not request_obj.subject and request_obj.message:
            request_obj.subject = request_obj.message[:160]
            update_fields.append("subject")
        if not request_obj.instruction and request_obj.message:
            request_obj.instruction = request_obj.message
            update_fields.append("instruction")

        target_status = "RESPONDED" if request_obj.is_answered else "PENDING"
        if request_obj.status != target_status:
            request_obj.status = target_status
            update_fields.append("status")

        if update_fields:
            request_obj.save(update_fields=update_fields)


class Migration(migrations.Migration):

    dependencies = [
        ('timeclock', '0009_servicereport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activityreportrequest',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activity_report_requests', to='timeclock.contract'),
        ),
        migrations.AddField(
            model_name='activityreportrequest',
            name='instruction',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='activityreportrequest',
            name='response_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_activity_report_requests', to='timeclock.servicereport'),
        ),
        migrations.AddField(
            model_name='activityreportrequest',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activityreportrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_activity_report_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activityreportrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('RESPONDED', 'Respondida'), ('REVIEWED', 'Revisada')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='activityreportrequest',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.RunPython(backfill_activity_request_status, migrations.RunPython.noop),
    ]
