# Generated by Django 6.0.2 on 2026-04-18 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_companyattendancepolicy_companyauthorizedlocation'),
        ('timeclock', '0010_activityreportrequest_contract_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='punch',
            name='confidence_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='punch',
            name='confidence_status',
            field=models.CharField(choices=[('FREE', 'Livre'), ('ON_SITE', 'No local'), ('OUT_OF_RADIUS', 'Fora do raio'), ('NO_LOCATION', 'Sem localizacao'), ('IMPRECISE', 'Localizacao imprecisa')], default='FREE', max_length=20),
        ),
        migrations.AddField(
            model_name='punch',
            name='distance_to_location_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='punch',
            name='geo_accuracy_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='punch',
            name='geo_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='punch',
            name='geo_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='punch',
            name='validated_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_punches', to='companies.companyauthorizedlocation'),
        ),
        migrations.AddField(
            model_name='punch',
            name='validation_method',
            field=models.CharField(choices=[('FREE_POLICY', 'Politica livre'), ('GEOLOCATION', 'Geolocalizacao'), ('PRESENTIAL_QR_PENDING', 'Presencial com QR (pendente)')], default='FREE_POLICY', max_length=30),
        ),
    ]
