# Generated by Django 6.0.2 on 2026-04-18 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_companyattendancepolicy_qr_requirement_and_more'),
        ('timeclock', '0011_punch_confidence_checked_at_punch_confidence_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='punch',
            name='qr_confirmation_status',
            field=models.CharField(choices=[('NOT_REQUIRED', 'Nao exigido'), ('CONFIRMED', 'Confirmado por QR'), ('REQUIRED_MISSING', 'QR exigido e nao confirmado')], default='NOT_REQUIRED', max_length=20),
        ),
        migrations.AddField(
            model_name='punch',
            name='qr_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='punch',
            name='qr_confirmed_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_confirmed_punches', to='companies.companyauthorizedlocation'),
        ),
    ]
