# Generated by Django 6.0.2 on 2026-04-18 19:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeclock', '0012_punch_qr_confirmation_status_punch_qr_confirmed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='punch',
            name='audit_event_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='punch',
            name='audit_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
