# Generated by Django 6.0.2 on 2026-05-21 00:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeclock', '0013_punch_audit_event_id_punch_audit_payload'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='punch',
            name='admin_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='punch',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='punch',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_punches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='punch',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PunchCorrectionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('time_changed', 'Horario corrigido'), ('cancelled', 'Cancelado'), ('restored', 'Restaurado'), ('admin_note_added', 'Observacao administrativa')], max_length=30)),
                ('old_datetime', models.DateTimeField(blank=True, null=True)),
                ('new_datetime', models.DateTimeField(blank=True, null=True)),
                ('old_status', models.CharField(blank=True, default='', max_length=30)),
                ('new_status', models.CharField(blank=True, default='', max_length=30)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='punch_correction_logs', to=settings.AUTH_USER_MODEL)),
                ('punch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='correction_logs', to='timeclock.punch')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['punch', '-created_at'], name='timeclock_p_punch_i_c6bad3_idx'), models.Index(fields=['action_type', '-created_at'], name='timeclock_p_action__f2f8bf_idx')],
            },
        ),
    ]
