# Generated by Django 6.0.2 on 2026-05-21 01:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0012_alter_employee_user_and_more'),
        ('timeclock', '0014_punch_admin_note_punch_cancelled_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PunchCorrectionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('problem_date', models.DateField()),
                ('problem_type', models.CharField(choices=[('extra_punch', 'Registro a mais'), ('missed_punch', 'Esqueci uma batida'), ('wrong_time', 'Horario errado'), ('duplicated_punch', 'Registro duplicado'), ('other', 'Outro')], max_length=30)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Aberta'), ('in_review', 'Em analise'), ('corrected', 'Corrigida'), ('rejected', 'Recusada')], default='open', max_length=20)),
                ('admin_response', models.TextField(blank=True, default='')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='punch_correction_requests', to='companies.company')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='punch_correction_requests', to='timeclock.contract')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='punch_correction_requests', to='companies.employee')),
                ('punch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correction_requests', to='timeclock.punch')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_punch_correction_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='punch_correction_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='timeclock_p_status_e1736a_idx'), models.Index(fields=['company', 'status'], name='timeclock_p_company_42c3b6_idx'), models.Index(fields=['employee', '-created_at'], name='timeclock_p_employe_765197_idx'), models.Index(fields=['problem_date'], name='timeclock_p_problem_96fcf4_idx')],
            },
        ),
    ]
