# Generated by Django 6.0.2 on 2026-05-22 01:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0013_company_internal_note_company_is_active_and_more'),
        ('timeclock', '0015_punchcorrectionrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('correction_request_created', 'Solicitacao de correcao criada'), ('correction_request_status_changed', 'Status de solicitacao alterado'), ('punch_corrected', 'Horario corrigido'), ('punch_cancelled', 'Registro cancelado'), ('punch_restored', 'Registro restaurado'), ('admin_note_added', 'Observacao administrativa adicionada'), ('company_acknowledged', 'Ciencia da empresa registrada')], max_length=50)),
                ('title', models.CharField(max_length=180)),
                ('message', models.TextField()),
                ('target_url', models.CharField(blank=True, default='', max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('company_acknowledged', models.BooleanField(default=False)),
                ('company_acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_internal_notifications', to=settings.AUTH_USER_MODEL)),
                ('company_acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_acknowledged_notifications', to=settings.AUTH_USER_MODEL)),
                ('recipient_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internal_notifications', to='companies.company')),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internal_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient_user', 'is_read', '-created_at'], name='timeclock_i_recipie_536444_idx'), models.Index(fields=['recipient_company', 'is_read', '-created_at'], name='timeclock_i_recipie_5bb83f_idx'), models.Index(fields=['notification_type', '-created_at'], name='timeclock_i_notific_bbdc93_idx'), models.Index(fields=['company_acknowledged', '-created_at'], name='timeclock_i_company_90aa83_idx'), models.Index(fields=['created_at'], name='timeclock_i_created_71ce53_idx')],
            },
        ),
    ]
