# Generated by Django 6.0.2 on 2026-06-03 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeclock', '0019_servicereport_hours_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicereport',
            name='conference_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='servicereport',
            name='conference_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicereport',
            name='conference_final_status',
            field=models.CharField(choices=[('PENDING', 'Aguardando conferencia'), ('VIEWED', 'Visualizado'), ('REVIEWED', 'Conferido'), ('REVOKED', 'Link revogado'), ('EXPIRED', 'Link expirado')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='servicereport',
            name='conference_first_viewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicereport',
            name='conference_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicereport',
            name='conference_revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
