# Generated by Django 6.0.2 on 2026-06-03 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeclock', '0020_servicereport_conference_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicereport',
            name='conference_final_status',
            field=models.CharField(choices=[('PENDING', 'Aguardando conferencia'), ('VIEWED', 'Visualizado'), ('REVIEWED', 'Conferido'), ('DIVERGENT', 'Com divergencia'), ('REVOKED', 'Link revogado'), ('EXPIRED', 'Link expirado')], default='PENDING', max_length=20),
        ),
    ]
