# Generated by Django 6.0.2 on 2026-06-04 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeclock', '0021_alter_servicereport_conference_final_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicereport',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
