# Generated by Codex on 2026-06-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timeclock", "0022_alter_servicereport_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicereport",
            name="whatsapp_sent_attempted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
