# Generated by Django 6.0.2 on 2026-06-05 16:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0015_company_contact_name_company_whatsapp'),
        ('timeclock', '0023_servicereport_whatsapp_sent_attempted_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkdayChangeLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('edited_date', models.DateField()),
                ('before_data', models.JSONField(blank=True, default=dict)),
                ('after_data', models.JSONField(blank=True, default=dict)),
                ('change_type', models.CharField(choices=[('edit', 'Edicao'), ('add', 'Adicao'), ('remove', 'Remocao'), ('client_changed', 'Troca de cliente'), ('mixed', 'Alteracao mista')], max_length=30)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=255)),
                ('note', models.TextField(blank=True, default='')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workday_change_logs', to='companies.company')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workday_change_logs', to='timeclock.contract')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workday_change_logs', to='companies.employee')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workday_change_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['edited_date', '-changed_at'], name='timeclock_w_edited__9f0ccf_idx'), models.Index(fields=['employee', '-changed_at'], name='timeclock_w_employe_5770fa_idx'), models.Index(fields=['company', '-changed_at'], name='timeclock_w_company_961f60_idx'), models.Index(fields=['change_type', '-changed_at'], name='timeclock_w_change__5d3c42_idx')],
            },
        ),
    ]
