# Generated by Django 6.0.2 on 2026-06-05 17:26

from django.db import migrations, models


def migrate_legacy_paid_status(apps, schema_editor):
    ServiceReport = apps.get_model("timeclock", "ServiceReport")
    for report in ServiceReport.objects.filter(status="PAID"):
        report.payment_status = "paid"
        report.paid_at = report.updated_at
        report.status = "VIEWED" if report.conference_first_viewed_at else "SENT"
        report.save(update_fields=["payment_status", "paid_at", "status"])


class Migration(migrations.Migration):

    dependencies = [
        ('timeclock', '0024_workdaychangelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicereport',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicereport',
            name='paid_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='servicereport',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('paid', 'Pago')], default='pending', max_length=20),
        ),
        migrations.RunPython(migrate_legacy_paid_status, migrations.RunPython.noop),
    ]
