# Generated by Django 6.0.2 on 2026-09-26 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeclock', '0025_servicereport_paid_at_servicereport_paid_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicereport',
            name='cancel_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='servicereport',
            name='canceled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
