# Generated by Django 6.0.2 on 2026-06-11 21:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0015_company_contact_name_company_whatsapp'),
        ('timeclock', '0025_servicereport_paid_at_servicereport_paid_note_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(max_length=90, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('icon_name', models.CharField(blank=True, default='', max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoria de servico',
                'verbose_name_plural': 'Categorias de servico',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('manual_client_name', models.CharField(blank=True, default='', max_length=120)),
                ('title', models.CharField(max_length=140)),
                ('description', models.TextField(blank=True, default='')),
                ('service_location', models.CharField(blank=True, default='', max_length=180)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('IN_PROGRESS', 'Em andamento'), ('FINISHED', 'Finalizado'), ('ARCHIVED', 'Arquivado')], default='DRAFT', max_length=20)),
                ('hourly_rate_snapshot', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fixed_labor_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('public_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_jobs', to='services.servicecategory')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_jobs', to='companies.company')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_jobs', to='timeclock.contract')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Servico',
                'verbose_name_plural': 'Servicos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['professional', 'status', '-created_at'], name='services_se_profess_77776e_idx'), models.Index(fields=['professional', 'category', '-created_at'], name='services_se_profess_037995_idx'), models.Index(fields=['professional', 'client', '-created_at'], name='services_se_profess_9bbdbc_idx')],
            },
        ),
    ]
