# Generated by Django 6.0.2 on 2026-06-12 01:40

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_seed_service_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceItemExpense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('MATERIAL', 'Material'), ('EXPENSE', 'Despesa'), ('PART', 'Peca'), ('TOLL', 'Pedagio'), ('FUEL', 'Combustivel'), ('PARKING', 'Estacionamento'), ('FOOD', 'Alimentacao'), ('OTHER', 'Outro')], default='MATERIAL', max_length=20)),
                ('name', models.CharField(max_length=140)),
                ('description', models.TextField(blank=True, default='')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('unit_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('usage_status', models.CharField(choices=[('PLANNED', 'Previsto'), ('PURCHASED', 'Comprado'), ('USED', 'Usado'), ('PARTIALLY_USED', 'Parcialmente usado'), ('NOT_USED', 'Nao usado'), ('RETURNED', 'Devolvido')], default='PLANNED', max_length=24)),
                ('receipt_note', models.CharField(blank=True, default='', max_length=180)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_expenses', to='services.servicejob')),
            ],
            options={
                'verbose_name': 'Item/despesa do servico',
                'verbose_name_plural': 'Itens/despesas do servico',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['service_job', 'usage_status', '-created_at'], name='services_se_service_90ac7a_idx'), models.Index(fields=['service_job', 'type', '-created_at'], name='services_se_service_95f190_idx')],
            },
        ),
        migrations.CreateModel(
            name='ServiceWorkLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('work_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=0)),
                ('description', models.CharField(blank=True, default='', max_length=180)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_logs', to='services.servicejob')),
            ],
            options={
                'verbose_name': 'Horario do servico',
                'verbose_name_plural': 'Horarios do servico',
                'ordering': ['-work_date', '-start_time', '-created_at'],
                'indexes': [models.Index(fields=['service_job', '-work_date', '-start_time'], name='services_se_service_e82da9_idx')],
            },
        ),
    ]
