# Generated by Django 6.0.2 on 2026-06-12 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_serviceitemexpense_serviceworklog'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicejob',
            name='public_report_first_viewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
