# Generated by Django 6.0.2 on 2026-06-12 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_servicejob_public_report_first_viewed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicejob',
            name='billing_mode',
            field=models.CharField(choices=[('HOURLY', 'Por hora'), ('FIXED', 'Valor fixo'), ('UNDEFINED', 'Sem valor definido ainda')], default='UNDEFINED', max_length=20),
        ),
        migrations.AddField(
            model_name='servicejob',
            name='manual_client_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='servicejob',
            name='manual_client_whatsapp',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='servicejob',
            name='planned_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicejob',
            name='planned_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicejob',
            name='service_city',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='servicejob',
            name='service_complement',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='servicejob',
            name='service_district',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='servicejob',
            name='service_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='servicejob',
            name='service_reference',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='servicejob',
            name='service_state',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AddField(
            model_name='servicejob',
            name='service_street',
            field=models.CharField(blank=True, default='', max_length=140),
        ),
        migrations.AddField(
            model_name='servicejob',
            name='service_zip_code',
            field=models.CharField(blank=True, default='', max_length=9),
        ),
    ]
