# Generated by Django 6.0.2 on 2026-06-15 22:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0015_company_contact_name_company_whatsapp'),
        ('services', '0009_service_item_catalog'),
        ('timeclock', '0025_servicereport_paid_at_servicereport_paid_note_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=120)),
                ('client_whatsapp', models.CharField(blank=True, default='', max_length=30)),
                ('client_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address_zipcode', models.CharField(blank=True, default='', max_length=9)),
                ('address_street', models.CharField(blank=True, default='', max_length=140)),
                ('address_number', models.CharField(blank=True, default='', max_length=20)),
                ('address_complement', models.CharField(blank=True, default='', max_length=80)),
                ('address_neighborhood', models.CharField(blank=True, default='', max_length=80)),
                ('address_city', models.CharField(blank=True, default='', max_length=80)),
                ('address_state', models.CharField(blank=True, default='', max_length=2)),
                ('address_reference', models.CharField(blank=True, default='', max_length=160)),
                ('title', models.CharField(max_length=140)),
                ('description', models.TextField(blank=True, default='')),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('preferred_time', models.TimeField(blank=True, null=True)),
                ('urgency', models.CharField(choices=[('LOW', 'Baixa'), ('NORMAL', 'Normal'), ('HIGH', 'Alta'), ('URGENT', 'Urgente')], default='NORMAL', max_length=20)),
                ('status', models.CharField(choices=[('NEW', 'Novo'), ('WAITING_INFO', 'Aguardando informacoes'), ('IN_REVIEW', 'Em analise'), ('CONVERTED', 'Transformado em servico'), ('REJECTED', 'Recusado'), ('ARCHIVED', 'Arquivado')], default='NEW', max_length=24)),
                ('source', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('PHONE', 'Ligacao'), ('REFERRAL', 'Indicacao'), ('OLD_CLIENT', 'Cliente antigo'), ('PUBLIC_LINK', 'Link publico'), ('OTHER', 'Outro')], default='WHATSAPP', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pedido de servico',
                'verbose_name_plural': 'Pedidos de servico',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_requests', to='services.servicecategory'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_requests', to='companies.company'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_requests', to='timeclock.contract'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='converted_service',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_request', to='services.servicejob'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['professional', 'status', '-created_at'], name='services_se_profess_7e0562_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['professional', 'category', '-created_at'], name='services_se_profess_2caf72_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['professional', 'source', '-created_at'], name='services_se_profess_03d270_idx'),
        ),
    ]
