# Generated by Django 6.0.2 on 2026-06-29 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_serviceitemcatalog_internal_code'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='servicerequestitem',
            new_name='services_se_service_dc4bba_idx',
            old_name='services_se_service_5958d7_idx',
        ),
    ]
