# Generated by Django 6.0.2 on 2026-10-07 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_rename_services_se_service_5958d7_idx_services_se_service_dc4bba_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicejob',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Rascunho'), ('PLANNED', 'Planejado'), ('SENT', 'Orçamento enviado'), ('SCHEDULED', 'Planejado'), ('IN_PROGRESS', 'Em execucao'), ('FINISHED', 'Finalizado'), ('REPORT_SENT', 'Relatorio enviado'), ('ARCHIVED', 'Arquivado')], default='DRAFT', max_length=20),
        ),
    ]
