# Generated by Codex on 2026-06-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="visual_theme",
            field=models.CharField(
                choices=[
                    ("graphite-premium", "Grafite Premium"),
                    ("professional-neutral", "Neutro Profissional"),
                    ("brazil-corporate", "Brasil Corporativo"),
                    ("rubro-professional", "Rubro Profissional"),
                ],
                default="graphite-premium",
                max_length=40,
            ),
        ),
    ]
