# Generated by Django 6.0.2 on 2026-09-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_visual_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='visual_theme',
            field=models.CharField(choices=[('graphite-premium', 'Grafite Premium'), ('professional-neutral', 'Neutro Profissional'), ('brazil-corporate', 'Brasil Corporativo'), ('rubro-professional', 'Rubro Profissional'), ('claro-operacional', 'Claro Operacional')], default='graphite-premium', max_length=40),
        ),
    ]
