# Generated by Django 6.0.2 on 2026-09-20 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_visual_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dismissed_tours',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
