DEFAULT_PLAYBOOK = {
    "document_title": "Proposta técnica / Ordem de serviço",
    "items_title": "Itens, recursos e despesas previstos",
    "scope_title": "Escopo combinado",
    "client_focus": "Conferir escopo, local, data, itens e valores antes da execução.",
    "checklist": [
        "Validar dados do cliente e local combinado.",
        "Conferir descrição do serviço e limites do escopo.",
        "Revisar itens, materiais, equipamentos ou despesas previstas.",
        "Confirmar valor estimado, valor fechado ou regra de cobrança por hora.",
        "Registrar períodos de execução e gerar relatório final ao concluir.",
    ],
    "logistics": [
        "Pedido recebido e organizado pelo prestador.",
        "Serviço planejado com data, local, escopo e itens previstos.",
        "Folha profissional enviada ao cliente para conferência.",
        "Execução registrada por períodos de trabalho.",
        "Relatório final enviado com o que foi realizado e cobrado.",
    ],
}


SERVICE_PLAYBOOKS = {
    "reformas-obras": {
        "document_title": "Memorial simples de execução",
        "items_title": "Materiais e etapas de execução",
        "scope_title": "Escopo da obra ou reforma",
        "client_focus": "Conferir ambiente, materiais, etapas, prazo e mudanças de escopo antes do início.",
        "checklist": [
            "Registrar ambiente ou área atendida.",
            "Descrever serviço, acabamento esperado e limites do combinado.",
            "Listar materiais previstos, mão de obra e despesas de apoio.",
            "Registrar prazo, data de início e etapas principais.",
            "Atualizar a folha se houver mudança de material, medida, prazo ou escopo.",
        ],
        "logistics": [
            "Cliente solicita reforma, reparo ou acabamento.",
            "Prestador faz visita ou coleta medidas e informações.",
            "Prestador monta memorial com escopo, materiais, etapas e estimativa.",
            "Cliente confere a folha e aprova o combinado operacional.",
            "Execução é registrada por períodos e o relatório final consolida horas, materiais e observações.",
        ],
    },
    "limpeza-conservacao": {
        "document_title": "Plano de atendimento",
        "items_title": "Produtos, recursos e áreas previstas",
        "scope_title": "Escopo da limpeza ou conservação",
        "client_focus": "Conferir áreas atendidas, tipo de limpeza, acesso ao local e duração estimada.",
        "checklist": [
            "Definir tipo de limpeza: residencial, comercial, pós-obra, recorrente ou pontual.",
            "Registrar áreas incluídas e exclusões importantes.",
            "Listar produtos, materiais e equipamentos necessários.",
            "Combinar acesso, horário, permanência e observações de segurança do local.",
            "Registrar execução e observações finais para comprovação do atendimento.",
        ],
        "logistics": [
            "Cliente informa local, tipo de ambiente e necessidade.",
            "Prestador monta plano com áreas, produtos, duração e valor.",
            "Cliente recebe link para conferência antes da visita.",
            "Durante a execução, o prestador registra períodos e observações.",
            "Relatório final resume o atendimento e itens usados.",
        ],
    },
    "jardinagem-paisagismo": {
        "document_title": "Plano de manutenção de área externa",
        "items_title": "Ferramentas, insumos e retirada prevista",
        "scope_title": "Escopo de jardinagem ou paisagismo",
        "client_focus": "Conferir área atendida, frequência, ferramentas, insumos e retirada de resíduos.",
        "checklist": [
            "Registrar área, tipo de jardim e acesso ao local.",
            "Definir corte, poda, plantio, irrigação simples ou manutenção periódica.",
            "Listar insumos como mudas, substrato, adubo ou materiais de apoio.",
            "Combinar retirada de resíduos verdes quando aplicável.",
            "Registrar períodos e observações do atendimento.",
        ],
        "logistics": [
            "Cliente informa área e necessidade de manutenção.",
            "Prestador define escopo, frequência e recursos necessários.",
            "Folha é enviada ao cliente para alinhar o combinado.",
            "Atendimento é executado e registrado.",
            "Relatório final mostra atividades, duração e itens aplicados.",
        ],
    },
    "marcenaria-serralheria": {
        "document_title": "Ordem de fabricação e instalação",
        "items_title": "Materiais, peças e etapas previstas",
        "scope_title": "Escopo de marcenaria ou serralheria",
        "client_focus": "Conferir medidas, material, acabamento, fabricação, instalação e prazo.",
        "checklist": [
            "Registrar medidas, local de instalação e referência visual quando houver.",
            "Descrever material, acabamento e função da peça ou estrutura.",
            "Listar ferragens, madeira, perfis, fixadores ou peças previstas.",
            "Separar etapa de fabricação, ajuste e instalação.",
            "Registrar alterações de medida ou acabamento antes da execução final.",
        ],
        "logistics": [
            "Cliente solicita ajuste, fabricação ou instalação.",
            "Prestador levanta medidas e materiais.",
            "Folha apresenta escopo, materiais, etapas e valor estimado.",
            "Execução é registrada por etapa.",
            "Relatório final confirma instalação, ajustes e itens usados.",
        ],
    },
    "assistencia-tecnica": {
        "document_title": "Ordem de serviço técnico",
        "items_title": "Peças, materiais e etapas previstas",
        "scope_title": "Diagnóstico e serviço técnico",
        "client_focus": "Conferir equipamento, defeito informado, diagnóstico inicial, peças e condições do atendimento.",
        "checklist": [
            "Identificar equipamento, marca, modelo ou referência quando possível.",
            "Registrar defeito informado pelo cliente.",
            "Descrever diagnóstico inicial e limite do atendimento.",
            "Listar peças, materiais, deslocamento e mão de obra prevista.",
            "Registrar testes realizados e observações no relatório final.",
        ],
        "logistics": [
            "Cliente informa problema técnico.",
            "Prestador abre ordem de serviço com diagnóstico inicial.",
            "Folha é enviada com peças, etapas e estimativa.",
            "Prestador registra execução, peças usadas e testes.",
            "Relatório final consolida o reparo e observações técnicas.",
        ],
    },
    "automotivo": {
        "document_title": "Ordem de serviço automotiva",
        "items_title": "Produtos, peças e deslocamento previstos",
        "scope_title": "Escopo do atendimento automotivo",
        "client_focus": "Conferir veículo, serviço, local, peças/produtos e tempo previsto.",
        "checklist": [
            "Registrar veículo ou identificação do atendimento.",
            "Descrever serviço: estética, acessório, inspeção ou manutenção leve.",
            "Listar produtos, peças, combustível ou deslocamento.",
            "Combinar local, horário e condições de acesso ao veículo.",
            "Registrar execução e observações finais.",
        ],
        "logistics": [
            "Cliente solicita atendimento automotivo fixo ou móvel.",
            "Prestador planeja serviço, local e recursos.",
            "Folha apresenta escopo, itens e estimativa.",
            "Execução é registrada por período.",
            "Relatório final confirma serviços e materiais aplicados.",
        ],
    },
    "beleza-bem-estar": {
        "document_title": "Plano de atendimento pessoal",
        "items_title": "Produtos e recursos do atendimento",
        "scope_title": "Escopo de beleza ou bem-estar",
        "client_focus": "Conferir procedimento, horário, duração, produtos e observações do atendimento.",
        "checklist": [
            "Definir procedimento ou pacote contratado.",
            "Registrar local, horário e duração estimada.",
            "Listar produtos, materiais descartáveis e recursos necessários.",
            "Registrar observações importantes do atendimento.",
            "Gerar relatório ou comprovante quando o serviço for concluído.",
        ],
        "logistics": [
            "Cliente agenda atendimento.",
            "Prestador define procedimento, tempo e valor.",
            "Folha confirma combinado e observações.",
            "Atendimento é executado e registrado.",
            "Relatório final ou comprovante resume o atendimento.",
        ],
    },
    "eventos-sonorizacao": {
        "document_title": "Proposta técnica para evento",
        "items_title": "Composição técnica inclusa",
        "scope_title": "Escopo do evento",
        "client_focus": "Conferir data, local, horários, equipamentos inclusos, operação, montagem, desmontagem e valor fechado.",
        "checklist": [
            "Registrar local, data e janela de montagem/operação/desmontagem.",
            "Listar equipamentos inclusos sem expor preço unitário quando for pacote fechado.",
            "Definir operação técnica, acompanhamento e desmontagem.",
            "Registrar sinal, saldo, condições e limites do pacote.",
            "No futuro, usar check-in opcional de presença no local combinado.",
        ],
        "logistics": [
            "Cliente informa evento, local, data e necessidade técnica.",
            "Prestador monta pacote com equipamentos, operação e valor fechado.",
            "Cliente recebe proposta técnica por link.",
            "Prestador registra montagem, operação e desmontagem por períodos.",
            "Relatório final confirma execução, horários e observações do evento.",
        ],
    },
    "fotografia-video": {
        "document_title": "Proposta de captação e entrega",
        "items_title": "Entregas, etapas e recursos previstos",
        "scope_title": "Escopo de fotografia ou vídeo",
        "client_focus": "Conferir briefing, local, captação, edição, quantidade de entregas e prazo.",
        "checklist": [
            "Registrar briefing e objetivo do material.",
            "Definir local, data, duração de captação e equipe quando houver.",
            "Listar entregas: fotos, vídeos, edição, cortes ou arquivos finais.",
            "Combinar prazo de entrega e revisões incluídas.",
            "Registrar execução, entrega e observações finais.",
        ],
        "logistics": [
            "Cliente solicita cobertura, ensaio ou conteúdo.",
            "Prestador define briefing, captação, edição e entregáveis.",
            "Folha é enviada para alinhar expectativa.",
            "Execução e pós-produção são registradas.",
            "Relatório final confirma entrega e pendências.",
        ],
    },
    "aulas-consultoria": {
        "document_title": "Plano de aula ou consultoria",
        "items_title": "Entregáveis, materiais e horas previstas",
        "scope_title": "Objetivo do atendimento",
        "client_focus": "Conferir objetivo, carga horária, temas, entregáveis e formato do atendimento.",
        "checklist": [
            "Definir objetivo do aluno, cliente ou empresa.",
            "Registrar temas, carga horária e formato presencial/remoto.",
            "Listar materiais de apoio, diagnóstico ou entregáveis.",
            "Combinar valor por hora, pacote ou projeto.",
            "Registrar sessões realizadas e evolução no relatório final.",
        ],
        "logistics": [
            "Cliente informa objetivo e necessidade.",
            "Prestador monta plano com temas, horas e entregas.",
            "Cliente recebe o plano para validação.",
            "Atendimentos são registrados por sessão ou período.",
            "Relatório final mostra progresso, horas e entregáveis.",
        ],
    },
    "administrativo-escritorio": {
        "document_title": "Plano de apoio administrativo",
        "items_title": "Atividades, entregáveis e recursos previstos",
        "scope_title": "Escopo administrativo",
        "client_focus": "Conferir demanda, prazo, horas previstas, entregáveis e cuidados com confidencialidade.",
        "checklist": [
            "Descrever demanda administrativa ou operacional.",
            "Definir prazo, prioridade e entregáveis.",
            "Registrar horas previstas e forma de acompanhamento.",
            "Anotar cuidados com documentos e confidencialidade.",
            "Gerar relatório por período ou entrega concluída.",
        ],
        "logistics": [
            "Cliente informa demanda de escritório, cadastro ou backoffice.",
            "Prestador organiza atividades e prazo.",
            "Folha confirma escopo e entregáveis.",
            "Trabalho é registrado por períodos.",
            "Relatório final resume horas e entregas realizadas.",
        ],
    },
    "seguranca-monitoramento": {
        "document_title": "Projeto técnico de instalação",
        "items_title": "Equipamentos, pontos e testes previstos",
        "scope_title": "Escopo de segurança e monitoramento",
        "client_focus": "Conferir pontos de instalação, equipamentos, cabos, configuração e testes.",
        "checklist": [
            "Registrar local e pontos previstos de instalação.",
            "Listar câmeras, alarmes, sensores, cabos, fontes ou conectores.",
            "Definir configuração, acesso e testes esperados.",
            "Registrar limites de cobertura e observações técnicas.",
            "Gerar relatório final com equipamentos instalados e testes realizados.",
        ],
        "logistics": [
            "Cliente solicita instalação ou manutenção de segurança.",
            "Prestador define pontos, equipamentos e configuração.",
            "Folha técnica é enviada para aprovação.",
            "Instalação é registrada por período e item usado.",
            "Relatório final confirma testes, pontos e observações.",
        ],
    },
}


def service_playbook_for(slug):
    data = SERVICE_PLAYBOOKS.get(slug, DEFAULT_PLAYBOOK)
    merged = DEFAULT_PLAYBOOK.copy()
    merged.update(data)
    return merged
