# Generated by Codex on 2026-03-08

from django.db import migrations, models


def copy_employee_company_to_m2m(apps, schema_editor):
    Employee = apps.get_model("companies", "Employee")
    for employee in Employee.objects.exclude(company_id__isnull=True).iterator():
        employee.companies.add(employee.company_id)


def copy_employee_m2m_to_company(apps, schema_editor):
    Employee = apps.get_model("companies", "Employee")
    for employee in Employee.objects.iterator():
        first_company = employee.companies.first()
        if first_company:
            employee.company_id = first_company.id
            employee.save(update_fields=["company"])


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0003_company_address_company_cnpj_company_logo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="companies",
            field=models.ManyToManyField(blank=True, related_name="employees", to="companies.company"),
        ),
        migrations.RunPython(copy_employee_company_to_m2m, copy_employee_m2m_to_company),
        migrations.RemoveField(
            model_name="employee",
            name="company",
        ),
    ]
