# Generated by Codex on 2026-03-24

import django.db.models.deletion
from django.db import migrations, models


def copy_employee_m2m_to_company_fk(apps, schema_editor):
    Employee = apps.get_model("companies", "Employee")
    for employee in Employee.objects.iterator():
        first_company = employee.companies.order_by("id").first()
        if first_company:
            employee.company_id = first_company.id
            employee.save(update_fields=["company"])


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0004_employee_companies_m2m"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employee_company_fk_temp",
                to="companies.company",
            ),
        ),
        migrations.RunPython(copy_employee_m2m_to_company_fk, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="employee",
            name="companies",
        ),
        migrations.AlterField(
            model_name="employee",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employees",
                to="companies.company",
            ),
        ),
    ]
