# Generated by Codex on 2026-03-24

from django.db import migrations, models
import django.db.models.deletion


def backfill_employee_company(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    Company = apps.get_model("companies", "Company")
    Employee = apps.get_model("companies", "Employee")
    Contract = apps.get_model("timeclock", "Contract")

    owner_email = "sistema.migracao@horacerta.local"
    owner_user, created = User.objects.get_or_create(
        email=owner_email,
        defaults={
            "username": owner_email,
            "role": "EMPRESA",
        },
    )
    if created:
        owner_user.password = "!"
        owner_user.save(update_fields=["password"])

    fallback_company, _created = Company.objects.get_or_create(
        owner=owner_user,
        name="Empresa nao vinculada",
        defaults={"email": None},
    )

    for employee in Employee.objects.filter(company_id__isnull=True).iterator():
        contract = (
            Contract.objects.filter(employee_user_id=employee.user_id)
            .order_by("-created_at")
            .first()
        )
        if contract:
            employee.company_id = contract.company_id
        else:
            employee.company_id = fallback_company.id
        employee.save(update_fields=["company"])


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0005_restore_employee_company_fk"),
        ("timeclock", "0006_punch_is_manual"),
        ("accounts", "0002_alter_user_email"),
    ]

    operations = [
        migrations.RunPython(backfill_employee_company, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="employee",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employees",
                to="companies.company",
            ),
        ),
    ]
