# Generated by Codex on 2026-04-17

from django.db import migrations


def seed_plans_and_features(apps, schema_editor):
    Plan = apps.get_model("companies", "Plan")
    Feature = apps.get_model("companies", "Feature")
    PlanFeature = apps.get_model("companies", "PlanFeature")

    plans_data = [
        {
            "code": "essencial",
            "name": "Essencial",
            "tier": 1,
            "description": "Plano base com recursos essenciais para operacao do HoraCerta.",
        },
        {
            "code": "pro",
            "name": "Pro",
            "tier": 2,
            "description": "Plano intermediario com visao ampliada e recursos premium de produtividade.",
        },
        {
            "code": "business",
            "name": "Business",
            "tier": 3,
            "description": "Plano avancado com recursos corporativos de auditoria e operacao premium.",
        },
    ]

    features_data = [
        {
            "code": "custom_themes",
            "name": "Temas customizados",
            "category": "experience",
            "required_role": "EMPRESA",
            "description": "Permite selecionar temas visuais premium adicionais por empresa.",
        },
        {
            "code": "advanced_reports",
            "name": "Relatorios avancados",
            "category": "reports",
            "required_role": "EMPRESA",
            "description": "Habilita relatorios e filtros de analise avancada.",
        },
        {
            "code": "incident_center",
            "name": "Centro de ocorrencias",
            "category": "operations",
            "required_role": "EMPRESA",
            "description": "Permite acompanhar e tratar ocorrencias operacionais.",
        },
        {
            "code": "accounting_access",
            "name": "Acesso contabil",
            "category": "operations",
            "required_role": "EMPRESA",
            "description": "Habilita recursos de apoio para fechamento contabil.",
        },
        {
            "code": "period_closing",
            "name": "Fechamento de periodo",
            "category": "operations",
            "required_role": "EMPRESA",
            "description": "Permite fechar periodos operacionais com controle de status.",
        },
        {
            "code": "audit_log",
            "name": "Log de auditoria",
            "category": "compliance",
            "required_role": "EMPRESA",
            "description": "Disponibiliza trilha de auditoria detalhada de eventos.",
        },
        {
            "code": "geo_clock",
            "name": "Ponto com geolocalizacao",
            "category": "timeclock",
            "required_role": "FUNCIONARIO",
            "description": "Permite registrar ponto com validacao de geolocalizacao.",
        },
        {
            "code": "qr_clock",
            "name": "Ponto por QR code",
            "category": "timeclock",
            "required_role": "FUNCIONARIO",
            "description": "Permite registrar ponto por leitura de QR code.",
        },
    ]

    plan_features = {
        "essencial": {
            "accounting_access",
            "period_closing",
        },
        "pro": {
            "accounting_access",
            "period_closing",
            "custom_themes",
            "advanced_reports",
            "incident_center",
        },
        "business": {
            "accounting_access",
            "period_closing",
            "custom_themes",
            "advanced_reports",
            "incident_center",
            "audit_log",
            "geo_clock",
            "qr_clock",
        },
    }

    plan_by_code = {}
    for item in plans_data:
        plan, _created = Plan.objects.update_or_create(
            code=item["code"],
            defaults={
                "name": item["name"],
                "tier": item["tier"],
                "description": item["description"],
                "is_active": True,
            },
        )
        plan_by_code[item["code"]] = plan

    feature_by_code = {}
    for item in features_data:
        feature, _created = Feature.objects.update_or_create(
            code=item["code"],
            defaults={
                "name": item["name"],
                "category": item["category"],
                "required_role": item["required_role"],
                "description": item["description"],
                "is_active": True,
            },
        )
        feature_by_code[item["code"]] = feature

    for plan_code, feature_codes in plan_features.items():
        plan = plan_by_code[plan_code]
        for feature_code in feature_codes:
            feature = feature_by_code[feature_code]
            PlanFeature.objects.update_or_create(
                plan=plan,
                feature=feature,
                defaults={"is_enabled": True},
            )


def rollback_seed_plans_and_features(apps, schema_editor):
    PlanFeature = apps.get_model("companies", "PlanFeature")
    Feature = apps.get_model("companies", "Feature")
    Plan = apps.get_model("companies", "Plan")

    PlanFeature.objects.all().delete()
    Feature.objects.filter(
        code__in=[
            "custom_themes",
            "advanced_reports",
            "incident_center",
            "accounting_access",
            "period_closing",
            "audit_log",
            "geo_clock",
            "qr_clock",
        ]
    ).delete()
    Plan.objects.filter(code__in=["essencial", "pro", "business"]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0007_feature_plan_companyfeatureoverride_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_plans_and_features, rollback_seed_plans_and_features),
    ]
