# Generated by Django 6.0.2 on 2026-04-18 18:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_seed_plans_features'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAttendancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validation_mode', models.CharField(choices=[('FREE', 'Livre'), ('GEOLOCATION', 'Com localizacao'), ('PRESENTIAL_QR', 'Presencial com QR')], default='FREE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_policy', to='companies.company')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_attendance_policies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company Attendance Policy',
                'verbose_name_plural': 'Company Attendance Policies',
            },
        ),
        migrations.CreateModel(
            name='CompanyAuthorizedLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('address_or_description', models.CharField(blank=True, default='', max_length=220)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('allowed_radius_m', models.PositiveIntegerField(default=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorized_locations', to='companies.company')),
            ],
            options={
                'verbose_name': 'Company Authorized Location',
                'verbose_name_plural': 'Company Authorized Locations',
                'ordering': ['name', '-updated_at'],
                'indexes': [models.Index(fields=['company', 'is_active'], name='companies_c_company_f52d44_idx'), models.Index(fields=['company', 'name'], name='companies_c_company_85eeae_idx')],
            },
        ),
    ]
