# Generated by Django 6.0.2 on 2026-04-18 19:03

import secrets
from django.db import migrations, models


def backfill_qr_tokens(apps, schema_editor):
    CompanyAuthorizedLocation = apps.get_model("companies", "CompanyAuthorizedLocation")
    used_tokens = set(
        token for token in CompanyAuthorizedLocation.objects.exclude(qr_token="").values_list("qr_token", flat=True)
    )
    for location in CompanyAuthorizedLocation.objects.all().iterator():
        if location.qr_token:
            continue
        token = secrets.token_hex(16)
        while token in used_tokens:
            token = secrets.token_hex(16)
        used_tokens.add(token)
        location.qr_token = token
        location.save(update_fields=["qr_token"])


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_companyattendancepolicy_companyauthorizedlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyattendancepolicy',
            name='qr_requirement',
            field=models.CharField(choices=[('NONE', 'Nao exigir QR'), ('FIRST_PUNCH', 'Exigir QR na primeira marcacao'), ('FIRST_AND_LAST', 'Exigir QR na primeira e ultima marcacao')], default='NONE', max_length=20),
        ),
        migrations.AddField(
            model_name='companyauthorizedlocation',
            name='qr_token',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.RunPython(backfill_qr_tokens, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='companyauthorizedlocation',
            name='qr_token',
            field=models.CharField(blank=True, default='', max_length=64, unique=True),
        ),
    ]
