# Generated by Django 6.0.2 on 2026-04-18 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_companyattendancepolicy_qr_requirement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyattendancepolicy',
            name='default_allowed_radius_m',
            field=models.PositiveIntegerField(default=120),
        ),
        migrations.AddField(
            model_name='companyattendancepolicy',
            name='default_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_attendance_policies', to='companies.companyauthorizedlocation'),
        ),
        migrations.AddField(
            model_name='companyattendancepolicy',
            name='require_location',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companyattendancepolicy',
            name='require_qr',
            field=models.BooleanField(default=False),
        ),
    ]
